# Generated by Django 4.0.6 on 2022-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlemodel',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre corto'),
        ),
    ]
