# Generated by Django 4.0.6 on 2022-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='line',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
