# Generated by Django 4.0.6 on 2022-07-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='context.shift', verbose_name='turno')),
                ('specialist_vc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esp_vc_1', to=settings.AUTH_USER_MODEL, verbose_name='especialista vc 1')),
                ('specialist_vc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esp_vc_2', to=settings.AUTH_USER_MODEL, verbose_name='especialista vc 2')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='context.team', verbose_name='equipo')),
            ],
        ),
    ]
