# Generated by Django 4.0.6 on 2022-07-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0002_bottlemodel_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gob', models.IntegerField(blank=True, null=True, verbose_name='longitud gota')),
                ('gob_max', models.IntegerField(blank=True, null=True, verbose_name='longitud gota max')),
                ('gob_min', models.IntegerField(blank=True, null=True, verbose_name='longitud gota min')),
                ('feeder', models.IntegerField(blank=True, null=True, verbose_name='temperatura derrame')),
                ('feeder_max', models.IntegerField(blank=True, null=True, verbose_name='temperatura derrame max')),
                ('feeder_min', models.IntegerField(blank=True, null=True, verbose_name='temperatura derrame min')),
                ('blank_side', models.IntegerField(blank=True, null=True, verbose_name='temperatura preparador')),
                ('blank_side_max', models.IntegerField(blank=True, null=True, verbose_name='temperatura preparador max')),
                ('blank_side_min', models.IntegerField(blank=True, null=True, verbose_name='temperatura preparador min')),
                ('finish_side', models.IntegerField(blank=True, null=True, verbose_name='temperatura terminador')),
                ('finish_side_max', models.IntegerField(blank=True, null=True, verbose_name='temperatura terminador max')),
                ('finish_side_min', models.IntegerField(blank=True, null=True, verbose_name='temperatura terminador min')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.production')),
            ],
        ),
    ]
