# Generated by Django 4.0.6 on 2022-07-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0002_bottlemodel_short_name'),
        ('context', '0002_alter_line_options_line_order'),
        ('working_shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='hora control')),
                ('working_shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='working_shift.workingshift', verbose_name='parte')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convoyer', models.BooleanField(blank=True, default=True, null=True, verbose_name='desfile / convoyer')),
                ('wheel', models.BooleanField(blank=True, default=True, null=True, verbose_name='paso por rueda')),
                ('cross', models.BooleanField(blank=True, default=True, null=True, verbose_name='cross convoyer')),
                ('lehr', models.BooleanField(blank=True, default=True, null=True, verbose_name='puesta en archa')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transport.transportcontrol', verbose_name='control')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='context.line', verbose_name='línea')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.production', verbose_name='producción')),
            ],
        ),
    ]
