# Generated by Django 4.0.6 on 2022-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='comments',
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
    ]
