# Generated by Django 4.0.6 on 2022-07-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_bottlemodel_short_name'),
        ('transport', '0002_remove_transport_comments_transportcontrol_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcontrol',
            name='convoyer_l11a',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L11A desfile / convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='convoyer_l11b',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L11B desfile / convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='convoyer_l12a',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L12A desfile / convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='convoyer_l12b',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L12B desfile / convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='convoyer_l13',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L13 desfile / convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='convoyer_l14',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L14 desfile / convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='cross_l11',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L11 cross convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='cross_l12',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L12 cross convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='cross_l13',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L13 cross convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='cross_l14',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L14 cross convoyer'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='lehr_l11',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L11 puesta en archa'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='lehr_l12',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L12 puesta en archa'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='lehr_l13',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L13 puesta en archa'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='lehr_l14',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L14 puesta en archa'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='production_l11a',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='prod_l11a', to='models.production', verbose_name='producción L11A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='production_l11b',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='prod_l11b', to='models.production', verbose_name='producción L11B'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='production_l12',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='prod_l12', to='models.production', verbose_name='producción L12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='production_l13',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='prod_l13', to='models.production', verbose_name='producción L13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='production_l14',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='prod_l14', to='models.production', verbose_name='producción L14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='wheel_l11',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L11 paso por rueda'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='wheel_l12',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L12 paso por rueda'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='wheel_l13',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L13 paso por rueda'),
        ),
        migrations.AddField(
            model_name='transportcontrol',
            name='wheel_l14',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='L14 paso por rueda'),
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
