# Generated by Django 4.0.6 on 2022-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transportcontrol_convoyer_l11a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcontrol',
            name='convoyer_l11a',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='desfile maquina A'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='convoyer_l11b',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='desfile maquina B'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='convoyer_l12a',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='desfile maquina A'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='convoyer_l12b',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='desfile maquina B'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='convoyer_l13',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='desfile'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='convoyer_l14',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='Desfile'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='cross_l11',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='cross convoyer'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='cross_l12',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='cross convoyer'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='cross_l13',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='cross convoyer'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='cross_l14',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='cross convoyer'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='lehr_l11',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='puesta en archa'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='lehr_l12',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='puesta en archa'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='lehr_l13',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='puesta en archa'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='lehr_l14',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='puesta en archa'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='wheel_l11',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='paso por rueda'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='wheel_l12',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='paso por rueda'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='wheel_l13',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='paso por rueda'),
        ),
        migrations.AlterField(
            model_name='transportcontrol',
            name='wheel_l14',
            field=models.BooleanField(blank=True, choices=[(True, 'OK'), (False, 'KO'), (None, ' ')], default=None, null=True, verbose_name='paso por rueda'),
        ),
    ]
